# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Run unit test"
  lane :run_unit_test do
    scan(scheme: "OdysseiaTests",
      output_types: "html",
      code_coverage: true,
      #prelaunch_simulator: true,
      output_directory: "fastlane/report/unit_test/",
      #derived_data_path: "build/",
      #fail_build: false,
      #slack_url: ENV["SLACK_WEB_HOOK_URL"],
      #slack_message: "Finish night time test 🚀"
    )
  end

  desc "Run ui test"
  lane :run_ui_test do
     scan(scheme: "OdysseiaUITests")
  end
end
